language: objective-c
osx_image: xcode61
rvm:
- 2.1.2
install:
- "travis_wait ./Scripts/install.sh"
script:
- "travis_wait ./Scripts/build.sh"
before_deploy:
- "./Scripts/package.sh"
deploy:
  provider: s3
  access_key_id: AKIAJ2ZYX3LNPAUI5IMQ
  secret_access_key:
    secure: RTrfhug2c1AD8QJ49W9wHaetRi3580QNhfDLQn98jOuaUUGiI/+LkNqhS64HTCT27m05VVykQX+ZFJAJtb6bVTg/GDKXrgmgYJ/P3VWk+qkgkDNBjMgf5hkjaj2aEu+2Dm0udxFky3gjpDC7XvVxhIzUsThxNRW/aBUSK03hd7U=
  bucket: dev.jonathan.porta.codes
  local-dir: pkg
  upload-dir: planet-hero
  skip_cleanup: true
  acl: public_read
  on:
    repo: JonathanPorta/planet-hero
notifications:
  slack:
    secure: QB8MA4SacK9JFNwGPKky/xUhDYXhxZpelfO1u/bhaoBfRVvaC+diUnCQGEs9B6cMTym8eyPUyJNlomrAkfUyFpeeQWh2lJgoFOzdgMKkoDFicgCWUdp3evtN53x5NfIwpP9D4dlneWYyib4ttLgVZllb48Zh7ulgABVyAtxv/vQ=
